### ISSUE TITLE
[BE] GET /my/reservations 응답 형식

### ISSUE THREAD

**Issue by junhea** [softeerbootcamp-3rd/Team1-driving-today#102]
## TO DO
 GET /my/reservations의 응답에  instructorId가 필요합니다
## Description
기존 응답 형식:
```json
{
  "reservationId": 1,
  "instructorImage": "instructor_image_1.jpg",
  "instructorName": "Instructor 1",
  "academyName": "Academy 1",
  "reservationDate": "2024-02-11",
  "reservationTime": 14,
  "trainingTime": 2
},
```
해당 응답을 기반으로 review를 작성하는데, 작성시 강사에 대한 간략한 정보가 표시됩니다.
이를 가져오기 위해서는 /instructors/{instructor_id} api를 사용해야 하므로 instructorId가 추가적으로 필요합니다

리뷰작성 폼 형태:
<img width="462" alt="image" src="https://github.com/softeerbootcamp-3rd/Team1-driving-today/assets/97426534/93a2308b-c490-45c2-99c7-5b4803591492">

**Comment by seojeewon** [comment]
추가하겠습니다

**Comment by junhea** [comment]
그리고 평점, 가입일도 필요해요!

**Comment by junhea** [comment]
가입일은 중요하지 않은 정보라고 판단해서 UI에서 제거할게요!
