### ISSUE TITLE
[BE] GET /reviews 응답 형식

### ISSUE THREAD

**Issue by ojj1123** [softeerbootcamp-3rd/Team1-driving-today#130]
## Description
cc. @jsLeen

- 리뷰 API 담당자인것 같아 멘션드립니다
- 리뷰 API 응답 형식에 사용자 프로필 이미지 URL이 필요합니다 (아래 디자인 확인)
<img width="445" alt="스크린샷 2024-02-15 오후 11 01 28" src="https://github.com/softeerbootcamp-3rd/Team1-driving-today/assets/33178048/999ad575-76b9-46f1-9b93-2b530c80f427">

- 현재 리뷰 API의 응답 형식은 아래와 같습니다. 사용자 프로필 이미지 URL 필드 추가 부탁드립니다
```json
[
  {
    "reviewId": 0,
    "contents": "string",
    "rating": 0,
    "createdAt": "2024-02-15T14:00:14.229Z",
    "reviewerName": "string"
  }
]
```

**Comment by jsLeen** [comment]
수정완료했습니다!
