### ISSUE TITLE
강사측 예약 내역 API에서 예정/완료 여부를 구분할 수 있는 방법이 필요합니다

### ISSUE THREAD

**Issue by junhea** [softeerbootcamp-3rd/Team1-driving-today#139]
## TO DO
강사측 대시보드 페이지에서는 거절이 가능한 (진행 예정인) 예약 요청 내역이 표시되고,
![image](https://github.com/softeerbootcamp-3rd/Team1-driving-today/assets/97426534/5001e1b7-52dc-48a0-80f2-fb1a9b5c7376)

예약 내역 페이지에서는 거절이 불가능한 (완료한) 예약 요청 내역이 표시됩니다.
![image](https://github.com/softeerbootcamp-3rd/Team1-driving-today/assets/97426534/03d44ea3-3f62-4753-bd0b-b7245c41db9e)

따라서 화면을 표시하기 위해서는 완료/예정 여부를 분리할 수 있는 API가 필요합니다.
하지만 현재 완료/예정 여부 관계없이 모두 보여주는 한개의 API만 존재합니다.
별도의 API 혹은 필터링 할 수 있는 방법을 구현할 예정인가요?
아니라면 화면 구성을 변경하도록 하겠습니다

**Comment by jsLeen** [comment]
화면이 구분되어 있으니까 프론트 입장에서 API가 구분되어 있는게 좋은가요? 그렇다면 두개로 분리하도록 수정 가능한데 의견 부탁드립니다.

**Comment by junhea** [comment]
둘중 어떠한 방식으로 해도 무관할 것 같아요! 편한대로 해주세요

**Comment by jsLeen** [comment]
기능 추가 완료했습니다. API는 이전처럼 1개로 유지했습니다.
 isUpcoming이 true면 예정된 예약이고, false면 완료된 예약입니다.

**Comment by jsLeen** [comment]
기존의 방식대로 하면 미래, 과거 예약이 섞여서 나와서 query parameter에서 조회 정보(미래 or 과거)를 받는 방식으로 수정했습니다.
