### ISSUE TITLE
feat: useSuspenseApiCall cache 정책

### ISSUE THREAD

**Issue by ojj1123** [softeerbootcamp-3rd/Team1-driving-today#181]
## TO DO

_https://github.com/softeerbootcamp-3rd/Team1-driving-today/pull/172#discussion_r1494565742_

**Comment by junhea** [comment]
간단하게 언마운트시 setTimeout으로 일정 시간이 지나면 캐시를 invalidate 하려고 하는데 어떻게 생각하세요?

**Comment by ojj1123** [comment]
사실 그렇게 하면 정확히는 `invalidate` 보다는 GC(Garbage Collection) 에 가까워요!
[cache invalidation 은 cache가 stale 해졌을 때 새로운 cache로 채우는 것을 의미해요](https://arc.net/l/quote/arcebdal)

어느쪽에 cache 를 우선 적용하고 싶으신가요??

**Comment by junhea** [comment]
덕분에 머리속에 좀 더 구체홛 된 것 같아요!
짧은시간안에 구현하기 쉽지 않아보이네요..
좀 더 고민해보고 최대한 단순하게 구현 해볼게요

**Comment by ojj1123** [comment]
너도 러프하게 생각한거라 페어로 같이 해봐요 :)

**Comment by ojj1123** [comment]
discussion 달아두고 아이디어 논의해봐요 !
