### ISSUE TITLE
useInfiniteFetch 아이템 삭제 인터페이스 추가

### ISSUE THREAD

**Issue by junhea** [softeerbootcamp-3rd/Team1-driving-today#182]
## TO DO
- 거절/삭제 가능한 리스트에서 필요

**Comment by ojj1123** [comment]
오오 이건 어떻게 구현할 생각인가요? 그냥 `refetch` 로직을 넣을 생각인가요?

**Comment by junhea** [comment]
몇가지 방법을 생각하고 있어요! 다만 refetch 방식에서 걱정되는건 오프셋 기반으로 페이징을 하다보니 인덱스가 꼬일수도 있을수도 있다는 것이에요

일단 이정도로 후보를 생각해 봤어요:
- 아이템이 해당되는 페이지 refetch
- 직접 원하는 아이템 삭제
- data를 직접 수정하지 않고 외부에서 filter로 한번 가공해서 사용
- data를 가공해서 사용하지 않고, 삭제할 경우 상태를 따로 두어 css로 해당 아이템 숨기기

**Comment by ojj1123** [comment]
## 결정사항

> data를 직접 수정하지 않고 외부에서 filter로 한번 가공해서 사용

- 거절 성공 시 filter 를 통해 데이터를 걸러줍니다. (새로고침하면 새로운 데이터를 받음)
- 거절 실패 시 filter 를 거치지 않습니다

**Comment by junhea** [comment]
#217
