### ISSUE TITLE
Loading 컴포넌트 스타일 주입

### ISSUE THREAD

**Issue by junhea** [softeerbootcamp-3rd/Team1-driving-today#183]
## TO DO
- 외부에서 스타일 주입할 수 있도록
- 재사용성 향상

**Comment by ojj1123** [comment]
@junhea 

이거 무한스크롤 때 만들었던 `Loading` 컴포넌트라 좀 작을거에요
혹시 `Skeleton` 컴포넌트는 어때요?
제가 전에 만들어둔 컴포넌트 있는데 그거 가져다 사용해도 좋구요
https://github.com/thismeme-team/thismeme-web/blob/develop/src/common/components/Skeleton/Skeleton.tsx

![스크린샷 2024-02-20 오전 12 13 28](https://github.com/softeerbootcamp-3rd/Team1-driving-today/assets/33178048/4ea46604-c764-44ea-83d1-d80fa8fd0712)

**Comment by ojj1123** [comment]
`fallback`에 컴포넌트 모양 딴 스켈레톤 UI 만들면 괜찮을거 같아용

**Comment by junhea** [comment]
저는 한번에 완벽한 결과물을 만들어내기 보다는 핵심적인 부분을 먼저 만들고 이를 조금씩 개선하는 편이에요!
현재 제가 작업중인 이슈의 핵심은 페이지내 api 요청에서 suspense를 활용하는 것이에요.
필요한 컴포넌트마다 fallback을 제작하는 것은 핵심이 아니라고 판단했어요!
반면에 로딩 컴포넌트는 이 빈자리를 채워줄 좋은 placeholder 였고요
그런데 해당 컴포넌트는 크기가 고정되어있고 이를 외부에서 수정할 수 있는 방법이 없어서 수정하려고요!
skeleton ui는 해당 이슈에서 다룰 문제가 아닌것 같아요
일단은 로딩을 최대한 활용해서 화면을 만들고
추후에 따로 이슈를 파서 skeleton ui를 구현하죠!

**Comment by ojj1123** [comment]
오우 제가 볼륨을 키울뻔했네요! `errorElement` 만들면 어떻냐는 의견 제안이랑 비슷한 느낌(?)이긴 했어요 ㅎㅎ

> 저는 한번에 완벽한 결과물을 만들어내기 보다는 핵심적인 부분을 먼저 만들고 이를 조금씩 개선하는 편이에요!

좋아요 저도 그렇게 해볼게요 ~

**Comment by junhea** [comment]
#258 의 스켈레톤 구현으로 불필요해짐
