### ISSUE TITLE
Skeleton UI와 ErrorBoundary

### ISSUE THREAD

**Issue by ojj1123** [softeerbootcamp-3rd/Team1-driving-today#258]
## TO DO

- [x] Skeleton UI (suspense 적용한 곳)
- [x] #186

## Description

- 아래와 같이 Suspense로 감싸주는 컴포넌트에서 Skeleton을 함께 묶어주어 처리할 예정입니다 (모듈을 통한 관심사 묶음)
```tsx
<Suspense fallback={<CardList.Skeleton />}>
  <CardList />
</Suspense>
```

**Comment by ojj1123** [comment]
@junhea 
`Errorboundary` 하면서 `Skeleton` 도 해두려는데 괜찮나요?
지금 `Loading` 컴포넌트 좀 어색하기도 하구요

**Comment by junhea** [comment]
좋아요!
react router의 error element는 로더 혹은 액션 실행 도중 발생한 오류를, error boundary는 페이지 내에서 발생한 오류를 처리하도록 구성하면 되겠네요
