### ISSUE TITLE
image optimization

### ISSUE THREAD

**Issue by ojj1123** [softeerbootcamp-3rd/Team1-driving-today#259]
## Description

- 웹 기본 기술로 이미지 최적화를 진행해봅니다.
- 이미지 렌더링 성능 개선, 사이즈, lazy loading 등을 서드파티 라이브러리 없이 최적화해봅니다. [참고](https://web.dev/articles/browser-level-image-lazy-loading?hl=ko)

**Comment by junhea** [comment]
프론트엔드만으로 할 수 있는 것에는 제한이 클것 같아요..
레이지로딩 정도는 해볼만 할 것 같네요!!
