### ISSUE TITLE
로그인 토큰 관련 이슈

### ISSUE THREAD

**Issue by ojj1123** [softeerbootcamp-3rd/Team1-driving-today#281]
## TO DO

cc. @junhea 
발표자료 제출하고 아래 부분 버그라 수정 필요해요!

 - [x] 만료된 토큰이 그대로 localstorage 에 남아있을 때 삭제되지 않고 계속 남아서 오류를 일으킴
> 대시보드 클릭하니까 에러페이지 발생 (localstorage에 만료된 토큰이 남아있어서 남)

- [x] 학원 검색 API에서 토큰을 보내는 API 함수 사용
- [x] 로그아웃 처리
- [x] 인증 인가 처리
  - [x] 인가 필요한 페이지 접속할 때마다 인가 검증 로직(`checkAuthLoader` 함수를 사용하고 있음)
  - [x] 인가 필요한 API호출 시 오류 처리 필요

**Comment by junhea** [comment]
왜 깃허브 이모티콘에는 눈물이 없죠🥲
