### ISSUE TITLE
path alias 적용

### ISSUE THREAD

**Issue by ojj1123** [softeerbootcamp-3rd/Team1-driving-today#30]
## TO DO
- [x] vite.config.js 의 `resolve.alias`
- [x] tsconfig.json 설정
- [x] eslint에서 path를 resolve할 수 있도록 설정

## Description
- module을 Import할 때 path alias 가 적용될 수 있도록 합니다

**Comment by junhea** [comment]
https://www.npmjs.com/package/eslint-import-resolver-typescripteslint에서도 alias를 resolve 하도록

**Comment by junhea** [comment]
참고해 주세요: [vite-&-ts-&-eslint-에서-import-alias-설정하기](https://github.com/softeerbootcamp-3rd/Team1-driving-today/wiki/vite-&-ts-&-eslint-%EC%97%90%EC%84%9C-import-alias-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)

**Comment by ojj1123** [comment]
정리해주셨군요..
참고해서 PR올릴게요 :)
