### ISSUE TITLE
star 컴포넌트 작성

### ISSUE THREAD

**Issue by junhea** [softeerbootcamp-3rd/Team1-driving-today#49]

**Comment by ojj1123** [comment]
https://mui.com/material-ui/react-rating/

`star` 컴포넌트를 `rating` 컴포넌트로 해도 괜찮겠네요!
material ui 참고해서 만들생각이었어요

**Comment by ojj1123** [comment]
use case 고려해서 `props` 를 생각해봤는데,
`readOnly` - 강사 상세정보에서 별점을 보여줄 때 `readOnly` 사용
`defaultValue` - 강사 상세정보에서 별점 보여줄 때 서버에서 내려준 별점을 `defaultValue` 에 넣어서 보여줌
drag 해서 별점 표시하도록 하면 좋을거같아요!

cc. @junhea

**Comment by junhea** [comment]
참고해서 만들어볼게요
좋은 자료 감사합니다🤗
