### ISSUE TITLE
Sidebar 컴포넌트 작성

### ISSUE THREAD

**Issue by ojj1123** [softeerbootcamp-3rd/Team1-driving-today#54]
## TO DO

- [x] sidebar icon 컴포넌트 사용
- [x] react router 와 함께 사용(path 가 active할 때 스타일링)

## Description
- component API (compound component pattern)
```tsx
<Sidebar.Root>
  <Sidebar.LinkList>
    <Sidebar.Link />
    <Sidebar.Link />
  <Sidebar.LinkList>
  <Sidebar.Footer><Sidebar.Footer>
<Sidebar.Root>
```

- design
<img width="702" alt="스크린샷 2024-02-12 오전 11 57 55" src="https://github.com/softeerbootcamp-3rd/Team1-driving-today/assets/33178048/60bec00b-2099-4e30-9219-462feff83bc4">

**Comment by ojj1123** [comment]
@junhea 
`Sidebar` 를 위와 같이 설계하려고 하는데 어떤가요?
`Header` 도 비슷한 인터페이스로 작성해볼 수 있을거같아요

**Comment by junhea** [comment]
컴파운드 패턴을 적절하게 잘 활용했네요! 추가로 Tab 컴포넌트도 비슷하게 가능할 것 같아요
