### ISSUE TITLE
Tab 컴포넌트 작성

### ISSUE THREAD

**Issue by junhea** [softeerbootcamp-3rd/Team1-driving-today#58]
## Description
- 참고: https://mui.com/material-ui/react-tabs/
![image](https://github.com/softeerbootcamp-3rd/Team1-driving-today/assets/97426534/a88d119b-c9dc-49cd-9882-ad3407fe9828)

**Comment by ojj1123** [comment]
`Material ui` 보고 참고하는거 좋아요!
다만 `Material ui` 는 다양한 어플리케이션을 커버하는 UI 컴포넌트 라이브러리에요.
저희 프로젝트에 맞게 필요한 use case 만 분석해서 하면 좋을거같아요! (이미 그렇게 하고 계신거 같네용ㅎㅎ)

compound component 패턴을 잘 활용한 라이브러리도 소개해드릴게요!
[radix-ui primitives](https://www.radix-ui.com/primitives)
여기에서 `tab` 컴포넌트가 있어요 [radix-ui tabs](https://www.radix-ui.com/primitives/docs/components/tabs#tabs)
cc. @junhea
